name: Push to branch

on:
  push: 
    branches: 
      - 'development'
      - 'production'
      
permissions:
  id-token: write
  contents: read
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Starting build job ..."
      - run: echo "The job has been triggered by a ${{github.event_name}} event."
      - run: echo "Let's checkout the repo"
      - uses: actions/checkout@v4
      - run: dotnet restore
      - run: dotnet publish
      - run: echo "It should be builded now."
      - run: zip all.zip *
      - run: echo "Uploading the artifact to the build environment."
      - uses: actions/upload-artifact@v4
        with:
          name: artifact-build
          path: ./all.zip
      - run: echo "Execution completed."
  deploy:
    needs: build
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting deploy job ..."
      - run: echo "The job has been triggered by a ${{github.event_name}} event."
      - run: echo "Let's download the zip file."
      - run: echo "${{secrets.AZURE_CRED}}"
      - uses: actions/download-artifact@v4
        with: 
          path: artifact-build
      - run: echo "Downloaded the zip file."
      - uses: azure/login@v2
        with: 
          # client-id: ${{secrets.AZURE_CLIENT_ID}}
          # tenant-id: ${{secrets.AZURE_TENANT_ID}}
          # subscription-id: ${{secrets.AZURE_SUB_ID}}
          creds: ${{ secrets.AZURE_CRED}}
          enable-AzPSSession: true
      - run: |
          az webapp deploy --resource-group ${{ secrets.RESOURCE_GROUP }} \
                          --name minimal-api \
                          --src-path ./publish
